### ISSUE TITLE
Query String & params methods

### ISSUE THREAD

**Issue by prof-alazhary** [xeioex/njs-examples#11]
Hi @xeioex 

If I'm going to handle an API `localhost:8080/api/12345?query=value1`  via Nginx config like
```config
location /api/:param {
js_content my_func;
}
```
How can I get access to the values of both the query string and param, in my js code `my_func`?

**Comment by prof-alazhary** [comment]
when trying to get the full URI, by `r.uri` I didn't find the query string in the URI .. ex for `/api/source?query1=value1&query2=value2` .
the `r.uri` would be `/api/source` only!

**Comment by tippexs** [comment]
The `uri` does not contain the arguments. You can use `request_uri` instead or use `args` to get the list of arguments.

**Comment by prof-alazhary** [comment]
thanks, @tippexs , but how I can use `request_uri` by njs code?

**Comment by xeioex** [comment]
@prof-alazhary 

You may access[ all the available nginx variables](http://nginx.org/en/docs/varindex.html), including `request_uri` using 
r.variables.xxx synxax. For example `r.variables.request_uri`. Request arguments are available as [r.variables.args](http://nginx.org/en/docs/http/ngx_http_core_module.html#var_args) (as a string) and r.args (as an object).

**Comment by tippexs** [comment]
Thanks @xeioex for being more specific!! 💪🏼

**Comment by prof-alazhary** [comment]
Thanks a lot @xeioex 
I really appreciate your responses :heart:
