### ISSUE TITLE
 js_body_filter & sendBuffer source change

### ISSUE THREAD

**Issue by tzukav** [xeioex/njs-examples#20]
Hello, is there any way to use js_body_filter and sendBuffer to remove some chars from the source? 
Nginx is waiting for the same content length, if the content length is changed(removed something), the page is keep loading without stopping.
One workaround I got is to replace those characters with a space, to get same content length.
Is there another workaround ? Preferably without js_content.
Thanks.

**Comment by xeioex** [comment]
Hi @tzukav,

You also have to[ set or drop](http://nginx.org/en/docs/http/ngx_http_js_module.html#js_body_filter) Content-Length altogether.
