### ISSUE TITLE
List of supported/included modules (require)

### ISSUE THREAD

**Issue by mStirner** [xeioex/njs-examples#4]
Is there a list of supported/included modules, like the `fs` ?
I could'nt find anything for this kind of topic.

Also is it possible to use a npm package, like the mongodb driver inside of njs ?

Thanks in advance.

**Comment by xeioex** [comment]
@mStirner  

the list of available modules are available [here](http://nginx.org/en/docs/njs/reference.html#built-in
). 

> Also is it possible to use a npm package, like the mongodb driver inside of njs ?

no, njs just implements some basic built-in node.js modules functionality.
But, with some effort it is possible to run some (which does not use node.js IO) node.js existing code using http://nginx.org/en/docs/njs/node_modules.html

**Comment by mStirner** [comment]
Thank you for the really quick response.
And thank you too for the links.

So it is currently not possible to connect to mongodb or any other tcp based service from njs ?

**Comment by xeioex** [comment]
@mStirner 

> So it is currently not possible to connect to mongodb or any other tcp based service from njs ?

no, currently the only way to get anything from the outside of the VM is r.subrequest() and "fs" module.

What problem are you trying to solve?

**Comment by mStirner** [comment]
I had the idea to store tokens in a database, if the token is in the database, its not revoked an possible valid and forward based on that the request to the API backend which validates the token more granular.

That was the one case where i actually would use it.

But it was more a question in general, out of curiosity.
Is it planned to support more "node" modules ? 

I read somewhere njs is not designed/implemented to make out of nginx a applications server, which is absolute understandable.
But a way to contact some other network app would be great. 

Is a seperate nginx module perhaps a better approach for this use case ?

**Comment by xeioex** [comment]
@mStirner 
> I read somewhere njs is not designed/implemented to make out of nginx a applications server, which is absolute understandable.

yes, because it would be outdated, feature poor wanna-be node.js, but there is already node.js. So, njs is designed to extend nginx, not to make something completely new out of it.

>But a way to contact some other network app would be great.

agree, but the nginx way is to use subrequests. If you can make a HTTP adaptor to your mongodb, you can already validate tokens using auth_request module (https://github.com/xeioex/njs-examples/blob/master/conf/http/complex_redirects.conf#L35).

**Comment by mStirner** [comment]
@xeioex Thats a really awesome idea. I will play with it a little bit around.
Question can be closed.

Thank you very much!

**Comment by xeioex** [comment]
@mStirner 

A more advanced solution something like this:
1) a combination of auth_request + njs (to validate and issue JWT temporary tokens) FAST PATH
2) if validation fails using [error_page](https://nginx.org/en/docs/http/ngx_http_core_module.html#error_page) to redirect to slow check (using subrequests)

Some additional info: https://github.com/nginxinc/nginx-openid-connect/blob/master/frontend.conf#L19

Note: auth_jwt is not available in nginx open source, but it can be implemented in njs if HS256 algorithm is used (albeit it would be several times slower, but it can be OK some configurations).
