### ISSUE TITLE
Docker version and some learning materials

### ISSUE THREAD

**Issue by soulteary** [xeioex/njs-examples#6]
Hi, @xeioex .

This project is awesome!

I created a project for NJS to save the docker image of the independent version: https://github.com/soulteary/docker-njs

Perhaps njs should provide developers with independent running executable files, instead of being limited to use in a container environment, it will be more convenient for development and debugging.

And aggregate njs-related content on GitHub, https://github.com/soulteary/njs-learning-materials .

Hope it will help njs grow, come on.

**Comment by xeioex** [comment]
@soulteary 

Cool!) We really appreciate it.

**Comment by soulteary** [comment]
Really thank you and your team for your dedication. @xeioex 

NJS is a technology stack that is currently seriously underestimated. It is lightweight and high-performance. It should be particularly SEXY as a serverless provider in the container era.

I have written a article describing [how to extract njs binaries files from the official docker images](https://soulteary.com/2021/01/10/let-us-start-with-the-mirroring-of-the-nginx-njs-tool-package.html), I look forward to your team’s independent executable files.

A document and demo will be completed soon describing how to use njs to simplify the implementation of node as a simple uml service.

If completed, I will submit the article and code to the learning materials project.

**Comment by soulteary** [comment]
The demo using njs to provide uml rendering is completed, and some minor problems were found in the process. Later, I will write an article describing the problems encountered in the process in detail.


Here is the project, you can have a try: https://github.com/soulteary/docker-nomnoml/
