### ISSUE TITLE
ambiguity in Docs

### ISSUE THREAD

**Issue by prof-alazhary** [xeioex/njs-examples#9]
Hi @xeioex 
I'd like to thank you first for your quick responses,

I'm coming from the njs references [docs](http://nginx.org/en/docs/njs/reference.html#ngx), and I've some questions.
I can see an example for the `ngx` obj, like
```
ngx.fetch('http://nginx.org/')
.then(reply => reply.text())
.then(body => r.return(200, body))
.catch(e => r.return(501, e.message))
```
It's very useful method,
but I can't figure out which [Directive](http://nginx.org/en/docs/http/ngx_http_js_module.html#directives) is suitable and valid to use this method `fetch`? it could be `js_content` ? I don't know
ex:
```
js_content my_func;
```
and if this is valid, what's the proper args could be passed to this callback `my_func`, and what is the return type?
It could be like this:
```js
function my_func (req,res){
return ngx.fetch(....)
}
```
?

**Comment by xeioex** [comment]
@prof-alazhary,

>what's the proper args could be passed to this callback my_func, and what is the return type?

my_func will accept an [nginx request object wrapper](http://nginx.org/en/docs/njs/reference.html#http).  See [this](http://nginx.org/en/docs/http/ngx_http_js_module.html#example) example. 

Return value is ignored. You have to use r.return(), or r.sendHeader() methods to prepare a Response.

**Comment by prof-alazhary** [comment]
Hi @xeioex , 
I'd like to ask you your advice on when I going to use `r.subrequest` vs `ngx.fetch`. in terms of the performance-wise and any other technical perspective. and the suitable use cases.
ex:
```
        location /token{
            js_content jsCode.covertTokenToCookie;
        }
        location /token_proxy {
            proxy_pass    https://60cf21844a030f0017f674c0.mockapi.io/token;
            proxy_ssl_server_name on;
        }
```
jsCode.js
```js
function covertTokenToCookie(r) {
    r.subrequest("/token_proxy", { method: "POST" },
        function (reply) {
           // TO DO MY LOGIC...
        }
    );
}
//OR
function covertTokenToCookie(r) {
    ngx.fetch("https://60cf21844a030f0017f674c0.mockapi.io/token", { method: "POST" }
    ).then((response)=>{
        // TO DO MY LOGIC...
    });
}

```
So what do you think? does their are equivalent? or there are pretty differences?

**Comment by prof-alazhary** [comment]
Also, I have another question :smile: 

how can I convert/parse the `r.requestBody` to a JSON, as you know its value is a string like this:
`req_body_field_1=abcddd&req_body_field_2=ccccccc` ? 
is there any built-in API to do this? or I have to implement my own method?

**Comment by xeioex** [comment]
@prof-alazhary 

>r.subrequest vs ngx.fetch. in terms of the performance-wise and any other technical perspective. and the suitable use cases.

`r.subrequest` is a built-in nginx feature and is preferred and better option in terms of configurability (for example, only for subrequest you can enable response caching). 

>how can I convert/parse the r.requestBody to a JSON, as you know its value is a string like this:
req_body_field_1=abcddd&req_body_field_2=ccccccc ?

All available modules are available [here](http://nginx.org/en/docs/njs/reference.html#builtin_modules), including [querystring](http://nginx.org/en/docs/njs/reference.html#querystring) module.

**Comment by xeioex** [comment]
@prof-alazhary 

BTW, since 0.7.2 you may use async/await for `r.subrequest` and `ngx.fetch`.

```js
let reply = await r.subrequest("/token_proxy", { method: "POST" });

// TO DO MY LOGIC...
```

**Comment by prof-alazhary** [comment]
Hi @xeioex 

how can we use the [Response](http://nginx.org/en/docs/njs/reference.html#response) interface? do we need to require something like `require('querystring')`?
